export default () => ({
    closeButton: {
        position: 'absolute',
        top: '15px',
        right: '24px',
        backgroundColor: 'transparent',
    },
    paperArea: {
        display: 'flex',
        paddingLeft: '20px',
    },
    navSection: {
        minWidth: '267px',
        marginTop: '40px',
        marginLeft: '40px',
        color: '#477C90',
        position: 'relative',
    },
    navTitle: {
        fontFamily: 'Poppins',
        fontWeight: 600,
        fontSize: '17px',
        letterSpacing: '0.02em',
        marginBottom: '29px',
    },
    navTopicItem: {
        marginBottom: '20px',
        color: '#477C90',
        textDecoration: 'none',
        fontFamily: 'Inter',
        fontWeight: 400,
        fontSize: '16px',
        letterSpacing: '0.01em',
        lineHeight: '19px',
        '&:hover': {
            cursor: 'pointer',
        },
    },
    navTopicItemSelected: {
        marginBottom: '20px',
        color: '#477C90',
        textDecoration: 'none',
        fontFamily: 'Inter',
        fontWeight: 600,
        fontSize: '16px',
        letterSpacing: '0.01em',
        lineHeight: '19px',
        '&:hover': {
            cursor: 'pointer',
        },
    },
    contentSection: {
        display: 'flex',
        padding: '0 50px',
        height: '635px',
        overflow: 'auto',
        '&::-webkit-scrollbar': {
            width: '7px',
            borderWidth: '0px 1px 1px 1px',
            borderStyle: 'solid',
            borderColor: '#B0B0B0',
        },
        '&::-webkit-scrollbar-track': {
            backgroundColor: '#CECECE',
        },
        '&::-webkit-scrollbar-thumb': {
            backgroundColor: '#2D83B1',
        },
    },
    contentTitle: {
        fontFamily: 'Poppins',
        fontWeight: '600',
        fontSize: '30px',
        lineHeight: '26px',
        letterSpacing: '-0.02em',
        marginTop: '40px',
        marginBottom: '20px',
        color: '#05555C',
    },
    sectionTitle: {
        fontFamily: 'Poppins',
        fontWeight: '600',
        fontSize: '25px',
        lineHeight: '26px',
        letterSpacing: '-0.02em',
        marginBottom: '20px',
        color: '#007A85',
    },
    mciContentContainer: {
        fontFamily: 'Inter',
        fontWeight: 400,
        fontSize: '16px',
        lineHeight: '22px',
    }
});