export const styles = () => ({
    container: {
        display: 'contents',
    },
    leftContainer: {
        borderRight: '1px solid #939393',
        padding: '34px 40px 20px 70px',
    },
    rightContainer: {
        padding: '34px 70px 20px 40px',
    },
    studyItem: {
        marginBottom: '33px',
    },
    studyItemTitle: {
        color: '#00818D',
        fontFamily: 'Poppins',
        fontSize: '16px',
        fontWeight: 500,
        lineHeight: '24px',
        letterSpacing: '0.32px',
        textTransform: 'uppercase',
    },
    studyItemContent: {
        color: '#000000',
        fontFamily: 'Inter',
        fontSize: '16px',
        fontWeight: 500,
        lineHeight: '22px',
        '& a': {
            color: '#455299',
            fontFamily: 'Inter',
            fontSize: '16px',
            fontStyle: 'normal',
            fontWeight: 700,
            lineHeight: '22px',
        },
    },
    exportIcon: {
        marginLeft: '8px',
    },
    studyManifestIcon: {
        marginLeft: '10px',
    },
    /* Consent codes box — matches global search cards + design reference */
    consentCodesBox: {
        backgroundColor: '#f0f4f7',
        border: '1px solid #8fa2b4',
        borderRadius: '2px',
        padding: '16px 18px',
        marginTop: '4px',
        /* Override studyItemContent & a for consent links + icon color */
        '& a': {
            color: '#4B5592',
            fontWeight: 600,
            fontSize: '14.25px',
            lineHeight: '18px',
            '&:hover': {
                color: '#3d456f',
            },
        },
    },
    consentCodesLabelRow: {
        display: 'flex',
        alignItems: 'baseline',
        gap: '3px',
        marginBottom: '10px',
    },
    consentCodesInnerLabel: {
        color: '#000000',
        fontFamily: 'Inter',
        fontWeight: 600,
        fontStyle: 'normal',
        fontSize: '15px',
        lineHeight: '100%',
        letterSpacing: '-0.02em',
        textAlign: 'center',
        verticalAlign: 'middle',
        leadingTrim: 'none',
    },
    consentHelpIcon: {
        width: '13px',
        height: '13px',
        fontSize: '13px',
        color: '#5a5a5a',
        cursor: 'help',
        flexShrink: 0,
        position: 'relative',
        top: '-0.42em',
        display: 'inline-block',
        verticalAlign: 'baseline',
        '& svg': {
            width: '13px',
            height: '13px',
            fontSize: '13px',
        },
    },
    consentCodeLine: {
        display: 'flex',
        alignItems: 'center',
        gap: '4px',
        marginBottom: '6px',
        '&:last-child': {
            marginBottom: 0,
        },
    },
    consentCodeLink: {
        fontFamily: 'Inter',
        fontSize: '14.25px',
        fontWeight: 600,
        lineHeight: '18px',
        letterSpacing: '0.32px',
        color: '#4B5592',
        textDecoration: 'underline',
        backgroundColor: 'transparent',
        '&:hover': {
            color: '#3d456f',
            textDecoration: 'underline',
            backgroundColor: 'transparent',
        },
    },
    consentExternalIcon: {
        fontSize: '16px',
        width: '16px',
        height: '16px',
        color: '#4B5592',
        flexShrink: 0,
    },
    /* Consent help tooltip — white panel, blue border, shadow, caret centered under icon */
    consentCodesTooltip: {
        backgroundColor: '#ffffff',
        color: '#000000',
        border: '1px solid #005EA2',
        borderRadius: '4px',
        boxShadow: '0px 2px 8px rgba(0, 0, 0, 0.15)',
        padding: 0,
        maxWidth: '380px',
        overflow: 'visible',
        margin: '6px 0',
    },
    consentTooltipBody: {
        position: 'relative',
        padding: '16px 18px',
        fontFamily: 'Poppins',
        fontSize: '13px',
        fontWeight: 400,
        fontStyle: 'normal',
        lineHeight: '17.5px',
        letterSpacing: '-0.01em',
        leadingTrim: 'none',
        textAlign: 'left',
        color: '#000000',
    },
    consentTooltipCaret: {
        position: 'absolute',
        left: '50%',
        bottom: '-6px',
        width: '10px',
        height: '10px',
        backgroundColor: '#ffffff',
        borderRight: '1px solid #005EA2',
        borderBottom: '1px solid #005EA2',
        borderTop: 'none',
        borderLeft: 'none',
        transform: 'translateX(-50%) rotate(45deg)',
        boxSizing: 'border-box',
        pointerEvents: 'none',
    },
    /* Tooltip above icon (placement top): arrow at bottom edge, points down */
    consentCodesTooltipPlacementTop: {
        '& $consentTooltipCaret': {
            top: 'auto',
            bottom: '-6px',
            borderRight: '1px solid #005EA2',
            borderBottom: '1px solid #005EA2',
            borderTop: 'none',
            borderLeft: 'none',
        },
    },
    /* Tooltip below icon (placement bottom, e.g. after Popper flip): arrow at top edge, points up */
    consentCodesTooltipPlacementBottom: {
        '& $consentTooltipCaret': {
            top: '-6px',
            bottom: 'auto',
            borderTop: '1px solid #005EA2',
            borderLeft: '1px solid #005EA2',
            borderRight: 'none',
            borderBottom: 'none',
        },
    },
});

