import gql from 'graphql-tag';
import landingImg from '../assets/landing/Hero_1.png'
import updateImg1 from '../assets/landing/Updates_1.png';
import updateImg2 from '../assets/landing/Updates_2.png';
import updateImg3 from '../assets/landing/Updates_3.png';
import aboutImg from '../assets/landing/About_1.png';
import wheel1 from '../assets/landing/card_ccdc.png';
import wheel2 from '../assets/landing/card_civic.png';
import wheel3 from '../assets/landing/card_mci.png';
import wheel4 from '../assets/landing/card_mtp.png';
import wheel5 from '../assets/landing/card_nccr.png';
import wheel6 from '../assets/landing/card_cgc.png';
import wheel7 from '../assets/landing/card_dbgap.png';

export const introData = {
  landingIntroPic: landingImg,
  introTitle1: 'Discover CCDI applications, data, resources, and other tools',
  introTitle2: 'Explore the CCDI Hub by selecting an available resource on the Hub Wheel',
  introTitle3: 'ABOUT CCDI HUB',
  introButtonTitle: 'ABOUT CCDI',
};

export const titleData = {
  latestUpdatesTitle: 'Latest Updates',
  resourceTitle: 'Explore',
  applicationsTitle: 'APPLICATIONS',
  cloudResourcesTitle: 'OTHER RESOURCES',
  aboutTitle: 'About the CCDI Community',
};

export const statsData = [
  {
    num: '203',
    title: 'Cataloged Datasets',
    detail: 'CCDC',
  },
  {
    num: '756',
    title: 'Participants',
    detail: 'MCI',
  },
  {
    num: '40,929',
    title: 'Molecular Targets',
    detail: 'MTP',
  },
  {
    num: '218,246',
    title: 'Cases',
    detail: 'NCCR Explorer',
  },
];

export const latestUpdatesData = [
  {
    img: updateImg1,
    title: 'NEW RELEASE FROM CCDC LOREM IPSUM DOLOR SIT AMET CON',
    content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna',
  },
  {
    img: updateImg2,
    title: 'CCDI IS ON THE NEWS!',
    content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna',
  },
  {
    img: updateImg3,
    title: 'LEARN MORE ABOUT LOREM IPSUM DOLOR SIT AMET CON',
    content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna',
  },
];

export const resourcesAppliationsListData = [
  {
    id: 'ccdc',
    title: 'Childhood Cancer Data Catalog',
    subtitle: 'CCDC',
    content: 'A searchable database of pediatric resources, sharing clinical care and research data generated by the pediatric cancer research community.',
    link: 'https://datacatalog.ccdi.cancer.gov',
  },
  {
    id: 'civic',
    title: 'Clinical Interpretation of Variants in Cancer',
    subtitle: 'CIViC',
    content: 'An open access, open source, community-driven web resource for Clinical Interpretation of Variants in Cancer.',
    link: 'https://civicdb.org',
  },
  {
    id: 'mci',
    title: 'Molecular Characterization Initiative for Childhood Cancers',
    subtitle: 'MCI',
    content: 'An Initiative providing molecular characterizations of solid tumors, soft tissue sarcomas, and rare diseases.',
    link: 'https://www.cancer.gov/research/areas/childhood/childhood-cancer-data-initiative/data-ecosystem/molecular-characterization',
  },
  {
    id: 'mtp',
    title: 'Molecular Targets Platform',
    subtitle: 'MTP',
    content: 'An instance of the Open Targets Platform with a focus on pediatric cancer data that allows users to browse and identify associations between molecular targets, diseases, and drugs.',
    link: 'https://moleculartargets.ccdi.cancer.gov',
  },
  {
    id: 'nccr',
    title: 'National Childhood Cancer Registry Explorer',
    subtitle: 'NCCR Explorer',
    content: 'A tool to browse demographic, incidence, and survival statistics for cancers in children and adolescent and young adults using NCCR data.',
    link: 'https://nccrexplorer.ccdi.cancer.gov',
  },
];

export const resourcesCloudListData = [
  {
    id: 'cgc',
    title: 'Cancer Genomics Cloud',
    subtitle: 'CGC',
    content: 'A cloud-based platform for cancer research data access, data analysis, and large-scale computational analyses.',
    link: 'https://www.cancergenomicscloud.org',
  },
  {
    id: 'dbgap',
    title: 'Database of Genotypes and Phenotypes',
    subtitle: 'dbGaP',
    content: 'A database to archive and distribute the data and results from studies of the interaction of genotype and phenotype in Humans.',
    link: 'https://www.ncbi.nlm.nih.gov/gap',
  },
];

export const aboutContainerData = {
  img: aboutImg,
  aboutButtonlist: ['CCDI HUB', 'CCDI', 'MCI'],
  aboutList: {
      'CCDI HUB': 'CCDI HUB',
      'CCDI': 'HELL0',
      'MCI': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi.ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque.',
  },
};

export const carouselList = [
  {
    img: wheel6,
    content: 'Cancer Genomics Cloud',
    link: 'https://www.cancergenomicscloud.org',
  },
  {
    img: wheel1,
    content: 'Childhood Cancer Data Catalog',
    link: 'https://datacatalog.ccdi.cancer.gov',
  },
  {
    img: wheel2,
    content: 'Clinical Interpretation of Variants in Cancer',
    link: 'https://civicdb.org',
  },
  {
    img: wheel7,
    content: 'Database of Genotypes and Phenotypes',
    link: 'https://www.ncbi.nlm.nih.gov/gap'
  },
  {
    img: wheel3,
    content: 'Molecular Characterization Initiative for Childhood Cancer',
    link: 'https://www.cancer.gov/research/areas/childhood/childhood-cancer-data-initiative/data-ecosystem/molecular-characterization',
  },
  {
    img: wheel4,
    content: 'Molecular Targets Platform',
    link: 'https://moleculartargets.ccdi.cancer.gov',
  },
  {
    img: wheel5,
    content: 'National Childhood Cancer Registry Explorer',
    link: 'https://nccrexplorer.ccdi.cancer.gov',
  },
];

export const GET_LANDING_PAGE_DATA_QUERY = gql`{
  numberOfPrograms
  numberOfStudies
  numberOfSubjects
  numberOfSamples
  numberOfFiles
  }
  `;